// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyedizvhnydbwtmskzpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5ZWRpenZobnlkYnd0bXNrenBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDg4MDMsImV4cCI6MjA2MzMyNDgwM30.uYMdG15DVUWH6alIv9sZpjtxDBayygYSskfLM6Yozlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);